### ISSUE TITLE
Fresh install but it will not work.

### ISSUE THREAD

**Issue by op6sie** [shibdib/EVE-Discord-Bot#56]
this is what i did step by step.

Install ubuntu 14.04 with options openssh and lamp
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y curl php5-cli git php5-mysqlnd libsqlite3-dev
sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
cd /var/www/
sudo git clone https://github.com/shibdib/EVE-Discord-Bot.git
cd EVE-Discord-Bot
sudo composer install
sudo git clone https://github.com/teamreflex/DiscordPHP
cd config
sudo cp config.new.php config.php

sudo apt-get install -y supervisor
supervisorctl restart
cd /etc/supervisor/conf.d
sudo mkdir -p /var/www/EVE-Discord-Bot/logs/

sudo touch discordbot.conf
sudo chmod 777 discordbot.conf
echo '[program:voc-discordbot]    
command=php /var/www/EVE-Discord-Bot/run.php    
autostart=true    
autorestart=true   
stopasgroup=true    
stderr_logfile=/var/www/EVE-Discord-Bot/logs/discordbot.err.log    
stdout_logfile=/var/www/EVE-Discord-Bot/logs/discordbot.out.log    
stdout_logfile_maxbytes=100KB    
stdout_logfile_backups=5    
stderr_logfile_maxbytes=100KB    
stderr_logfile_backups=5' > discordbot.conf

sudo chmod 644 discordbot.conf
sudo supervisorctl update
sudo supervisorctl start voc-discordbot

Just like the install guide (https://github.com/shibdib/EVE-Discord-Bot/wiki/2.-Installation) tells me to.
what did i miss or had to do (and is not on the page)?

thanks.

**Comment by daschalki** [comment]
Make sure you have pdo_sqlite installed too (php5-sqlite)
as soon as pdo_sqlite shows up at php -m it should be working

**Comment by op6sie** [comment]
It does show up, tried to reinstall but same error.

Cheers
Op 13 jun. 2016 9:47 a.m. schreef "daschalki" <notifications@github.com>:

**Comment by op6sie** [comment]
When i get Home this evening i will start over and check this again.
Well sent the 2 logfiles also then
Op 13 jun. 2016 10:40 a.m. schreef "Tonny de Groot" <op6sie@gmail.com>:

**Comment by op6sie** [comment]
ok i got some further needed to setup de mysql database to get it to work past the got no driver error

now i have this...

PHP Fatal error:  require_once(): Failed opening required '/var/www/EVE-Discord-Bot/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/EVE-Discord-Bot/run.php on line 28

no vendor folder in the EVE-Discord-Bot folder.
how do i get it?

Cheers Tonny.

**Comment by daschalki** [comment]
./vendor shows up for me directy after using "install composer"
maybe run composer again and check for errors.

**Comment by op6sie** [comment]
Will do so at work 😂 love work this way
Op 14 jun. 2016 6:57 a.m. schreef "daschalki" <notifications@github.com>:

**Comment by op6sie** [comment]
After reinstalling i got a bunch of other errors it seems like the Program
can't decide what database to use i use MySQL not sqlite. This Evening i
sent you the terminal log of all the things i have done. It gives you more
info i guess to help in this problem.

The Programs the bot is build with is not my thing as you migth have guest.

Cheers Tonny
Op 14 jun. 2016 6:58 a.m. schreef "Tonny de Groot" <op6sie@gmail.com>:

**Comment by daschalki** [comment]
There are different databases afaik.
sqlite is used for the database files in /database
and mysql is used for the database you specify in the config that stores the userdata.

**Comment by shibdib** [comment]
sudo apt-get install php5-sqlite

should resolve the no driver error

**Comment by op6sie** [comment]
the installation is still missing something.

reinstalled the stuff and the driver error is gone but this is the current error...

tonny@discord:/var/www/EVE-Discord-Bot/logs$ cat discordbot.err.log
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: storage' in /var/www/EVE-Discord-Bot/library/Db.php:68
Stack trace:
#0 /var/www/EVE-Discord-Bot/library/Db.php(68): PDO->prepare('SELECT value FR...')
#1 /var/www/EVE-Discord-Bot/library/permCache.php(43): dbQueryField('SELECT value FR...', 'value', Array)
#2 /var/www/EVE-Discord-Bot/run.php(41): getPermCache('initialInstall')
#3 {main}
  thrown in /var/www/EVE-Discord-Bot/library/Db.php on line 68
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: storage' in /var/www/EVE-Discord-Bot/library/Db.php:68
Stack trace:
#0 /var/www/EVE-Discord-Bot/library/Db.php(68): PDO->prepare('SELECT value FR...')
#1 /var/www/EVE-Discord-Bot/library/permCache.php(43): dbQueryField('SELECT value FR...', 'value', Array)
#2 /var/www/EVE-Discord-Bot/run.php(41): getPermCache('initialInstall')
#3 {main}
  thrown in /var/www/EVE-Discord-Bot/library/Db.php on line 68
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: storage' in /var/www/EVE-Discord-Bot/library/Db.php:68
Stack trace:
#0 /var/www/EVE-Discord-Bot/library/Db.php(68): PDO->prepare('SELECT value FR...')
#1 /var/www/EVE-Discord-Bot/library/permCache.php(43): dbQueryField('SELECT value FR...', 'value', Array)
#2 /var/www/EVE-Discord-Bot/run.php(41): getPermCache('initialInstall')
#3 {main}
  thrown in /var/www/EVE-Discord-Bot/library/Db.php on line 68
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: storage' in /var/www/EVE-Discord-Bot/library/Db.php:68
Stack trace:
#0 /var/www/EVE-Discord-Bot/library/Db.php(68): PDO->prepare('SELECT value FR...')
#1 /var/www/EVE-Discord-Bot/library/permCache.php(43): dbQueryField('SELECT value FR...', 'value', Array)
#2 /var/www/EVE-Discord-Bot/run.php(41): getPermCache('initialInstall')
#3 {main}
  thrown in /var/www/EVE-Discord-Bot/library/Db.php on line 68

**Comment by shibdib** [comment]
now that you have all the necessary background stuff delete the entire bot folder (feel free to save ur config) and redownload the bot

**Comment by op6sie** [comment]
[[Tonny@JAMMERHOOR] 033 discordbot (20160618115945).txt](https://github.com/shibdib/EVE-Discord-Bot/files/321684/Tonny.JAMMERHOOR.033.discordbot.20160618115945.txt)

**Comment by op6sie** [comment]
the actions i have done are in the file results are diffrent but still a error.
